# Generated by Django 5.2.1 on 2025-05-18 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_issue', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In progress', 'In progress'), ('Resolved', 'Resolved'), ('Suspended', 'Suspended')], default='Open')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogHandlerApp.issuebin')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateField()),
                ('log_raw', models.TextField()),
                ('Issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogHandlerApp.issue')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('line_raw', models.TextField()),
                ('Log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogHandlerApp.log')),
            ],
        ),
    ]
