# Generated by Django 5.2.1 on 2025-05-25 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueBin',
            fields=[
                ('project_name', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In progress', 'In progress'), ('Resolved', 'Resolved'), ('Suspended', 'Suspended')], default='Open', max_length=20)),
                ('log_raw', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogHandlerApp.issuebin')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('line_raw', models.TextField()),
                ('Issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogHandlerApp.issue')),
            ],
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('Issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogHandlerApp.issue')),
            ],
        ),
    ]
