# Generated by Django 5.2.1 on 2025-05-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogHandlerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebin',
            name='project_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
