# Generated by Django 5.2.1 on 2025-05-20 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogHandlerApp', '0002_alter_log_log_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='log_raw',
            new_name='line_raw',
        ),
        migrations.RemoveField(
            model_name='log',
            name='log_time',
        ),
        migrations.AddField(
            model_name='issue',
            name='log_raw',
            field=models.TextField(default='trololololo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='line_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creation_time', models.DateTimeField(auto_now_add=True)),
                ('Issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogHandlerApp.issue')),
            ],
        ),
        migrations.DeleteModel(
            name='Line',
        ),
    ]
