# Generated by Django 5.2.1 on 2025-05-26 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogHandlerApp', '0003_logfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
