# Generated by Django 5.2.1 on 2025-05-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogHandlerApp', '0003_rename_log_raw_log_line_raw_remove_log_log_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebin',
            name='project_name',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
