# Generated by Django 5.2.1 on 2025-05-27 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogHandlerApp', '0004_logfile_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logfile',
            name='upload_date',
        ),
    ]
