# Generated by Django 5.2.1 on 2025-05-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogHandlerApp', '0004_issuebin_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='pointelessTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='occurrence',
            old_name='Creation_time',
            new_name='creation_time',
        ),
        migrations.RemoveField(
            model_name='issuebin',
            name='latest_issue',
        ),
    ]
