# Generated by Django 5.2.1 on 2025-05-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogHandlerApp', '0005_remove_logfile_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In progress', 'In progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Suspended', 'Suspended')], default='Open', max_length=20),
        ),
    ]
