# Generated by Django 5.2.1 on 2025-05-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogHandlerApp', '0005_pointelesstest_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pointelessTest',
        ),
    ]
