version: '3'
services:
  web:
    build: .
    ports:
    - "8000:8080"
    tty: True
    networks:
      - service_network
    environment:
      - PIPELINE=production   #change before deploying in prod
      - SECRET_KEY=production  #change before deploying in prod
      - DB_NAME=build_log_db
      - DB_USER_NM=postgres #change before deploying in prod
      - DB_USER_PW=toor   #change before deploying in prod
      - DB_IP=db
      - DB_PORT=5432
      - DJANGO_SUPERUSER_PASSWORD=toor  #change before deploying in prod
    depends_on:
    - db
  db:
   image: bitnami/postgresql:latest
   volumes:
     - ./postgres:/bitnami/postgresql
   networks:
    - service_network
   ports:
     - "5432:5432"
   environment:
    - POSTGRESQL_PASSWORD=toor   #change before deploying in prod
    - POSTGRESQL_USERNAME=postgres #change before deploying in prod
    - POSTGRESQL_DATABASE=build_log_db
networks:
  service_network:

